---
version: 1

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt

additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN pip install ansible-lint
    - RUN pip install molecule
