---
collections:
  - name: amazon.aws
  - name: theforeman.foreman
  - name: community.vmware
  - name: ansible.posix
  - name: redhatinsights.insights
  - name: community.mysql
  - name: epfl_si.rhel
    version: 1.8.2
    source: https://galaxy.ansible.com
  # - name: redhat.rhel_system_roles
  #   version: 1.0.1
  #   source: https://cloud.redhat.com/api/automation-hub/
